const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const COMPLETED_TODO = "COMPLETED_TODO";

const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
const CLOSED_SIDEBAR = "CLOSED_SIDEBAR";
const OPEN_SIDEBAR = "OPEN_SIDEBAR";

export {
  ADD_TODO,
  DELETE_TODO,
  COMPLETED_TODO,
  TOGGLE_SIDEBAR,
  CLOSED_SIDEBAR,
  OPEN_SIDEBAR,
};
